### ISSUE TITLE
zcash daemon has single connection (logs show attempts to peer with tor nodes)

### ISSUE THREAD

**Issue by djpnewton** [Electric-Coin-Company/zcash#673] opened 2016-01-26 22:53 UTC
After running a few days I only ever connect to the alphatestnet.z.cash peer

The log contains lots of these:

```
2016-01-26 22:51:56 Cannot connect to i6y6ivorwakd7nw3.onion:18333: unsupported
network
```

**Comment by ebfull** [comment] 2016-01-26 22:58
Closing as duplicate of #651.

**Closed by ebfull** 2016-01-26 22:58 UTC

**Comment by djpnewton** [comment] 2016-01-26 23:21
Will solving the attempted onion connections solve the single peer issue too?

**Comment by ebfull** [comment] 2016-01-27 01:27
There may not be a lot of users connected to the testnet node, or they may be configured to only connect to the testnet node.

**Comment by djpnewton** [comment] 2016-01-27 01:36
I guess so, seems odd, the difficulty went up, someones producing blocks. why are they hiding =)
